In [1]:
import numpy as np

In [2]:
score = np.array([0.5, 0.3, 0.9, 0.6, 0.2, 0.4])
I = np.argsort(score)

In [3]:
under_thr_i= np.where(score[I] > 0.4)[0]

In [4]:
I = np.delete(I, np.arange(under_thr_i[0]))

In [5]:
score[I]

array([0.5, 0.6, 0.9])

In [61]:
pc = np.array([[0,1,1],[0,0,1],[1,0,0],[0,1,0],[3,4,5]])

In [62]:
n = pc.shape[0]
x = np.tile(np.expand_dims(pc,1), [1,n,1])
y = np.empty((n,n,3))
y[:] = np.tile(np.expand_dims(pc,0), [n,1,1])
dist = np.sum((x - y) ** 2, axis=2) ** 0.5 # n by n matrix

In [92]:
np.where(close_pts_arr[0])[0]

array([0, 1, 3])

In [97]:
instances_list = []
thr = 1.5
close_pts_arr = np.where(dist < thr, True, False)
for i in range(n):
    included = False
    for inst in instances_list:
        if i in inst:            
            included = True
            break            
    if not included:
        instances_list.append(set(np.where(close_pts_arr[i])[0]))
        
for i in range(len(instances_list)):
    for j in range(i+1,len(instances_list)):
        if len(instances_list[i].intersection(instances_list[j])) > 0:
            instances_list[i] = instances_list[i].union(instances_list[j])
            instances_list[j] = set()

In [98]:
instances_list

[{0, 1, 2, 3}, set(), {4}]

In [88]:
instances_list = []
thr = 1.5
close_pts_arr = np.where(dist < thr, True, False)
close_pts_list = [list(np.where(close_pts_arr[i])[0]) for i in range(len(close_pts_arr))]
for i in range(n):
    included = False
    new_pts = close_pts_list[i]
    for inst in instances_list:
        if i in inst:            
            inst.extend(new_pts)
            included = True
    if not included:
        instances_list.append(new_pts)

instances_list = [set(inst) for inst in instances_list]

for i in range(len(instances_list)):
    for j in range(i+1,len(instances_list)):
        if len(instances_list[i].intersection(instances_list[j])) > 0:
            instances_list[i] = instances_list[i].union(instances_list[j])
            instances_list[j] = set()

#    if sum([len(inst) for inst in instances_list]) == n: break

In [89]:
instances_list

[{0, 1, 2, 3}, {4}]

In [80]:
instances_list

[{0, 1, 2, 3}, set(), {4}]

In [27]:
instances_list = []
thr = 2
#close_pts_list = [set(np.where(dist[j,:] < thr)[0]) for j in range(n)]
close_pts_arr = np.where(dist < thr, True, False)[0]

for i in range(1, n):    
    included = False
    for inst_set in instances_list:
        if i in inst_set:
            included = True
            break
    if not included:
        close_pts = set()           
        q = [i]
        while q:
            j = q.pop()
            #if j in close_pts: continue
            #new_pts = close_pts_list[j]
            new_pts = set(np.where(close_pts_arr[j])[0])
            print(new_pts)
            add_pts = new_pts - close_pts
            q += list(add_pts)
            close_pts = close_pts.union(add_pts)
        
        instances_list.append(close_pts)
centroids = []
for s in instances_list:
    cent = np.mean(pc[list(s),:], axis=0)
    centroids.append(cent)
    
    

{0}
{0}
{0}
{0}
set()


In [29]:
dist

array([[0.        , 1.41421356, 1.41421356, 6.40312424],
       [1.41421356, 0.        , 1.41421356, 6.70820393],
       [1.41421356, 1.41421356, 0.        , 6.55743852],
       [6.40312424, 6.70820393, 6.55743852, 0.        ]])

In [26]:
centroids

[array([0., 0., 1.]), array([0., 0., 1.]), array([nan, nan, nan])]

In [15]:
a = np.where(dist < thr, True, False)

In [18]:
a[0]

array([ True,  True,  True, False])

In [22]:
set(np.where(a[0])[0])

{0, 1, 2}

In [9]:
dist

array([[0.        , 1.41421356, 1.41421356, 6.40312424],
       [1.41421356, 0.        , 1.41421356, 6.70820393],
       [1.41421356, 1.41421356, 0.        , 6.55743852],
       [6.40312424, 6.70820393, 6.55743852, 0.        ]])